### ISSUE TITLE
POST get_channel_aggregate_data : 400 Channel does not exist when commenting on a public document

### ISSUE THREAD

**Issue by almereyda** [docs-plus/docs.plus#142]
When anonymously writing on https://docs.plus/ul6pxw700c I've found I couldn't open some kind of chat drawer after selecting text and wanting to comment on it.

![image](https://github.com/user-attachments/assets/32c015ab-030c-4fa3-8f1f-711f874c023c)

Request

```yaml
POST /rest/v1/rpc/get_channel_aggregate_data HTTP/3
Host: hocjpflweuppomwqkdui.supabase.co
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:133.0) Gecko/20100101 Firefox/133.0
Accept: application/vnd.pgrst.object+json
Accept-Language: de,en-GB;q=0.8,fr;q=0.6,en;q=0.4,en-US;q=0.2
Accept-Encoding: gzip, deflate, br, zstd
Content-Type: application/json
Content-Length: 58
apikey: something
content-profile: public
x-client-info: supabase-ssr/0.5.2
Origin: https://docs.plus
DNT: 1
Sec-GPC: 1
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: cross-site
authorization: Bearer another thing
Connection: keep-alive
Priority: u=4
Pragma: no-cache
Cache-Control: no-cache
TE: trailers
```

Response

```yaml
HTTP/3 400 
date: Sat, 14 Dec 2024 16:18:15 GMT
content-type: application/json; charset=utf-8
cf-ray: 8f1f8241aef0e513-TXL
cf-cache-status: DYNAMIC
access-control-allow-origin: https://docs.plus
content-encoding: gzip
strict-transport-security: max-age=31536000; includeSubDomains
vary: Accept-Encoding
access-control-expose-headers: Content-Encoding, Content-Location, Content-Range, Content-Type, Date, Location, Server, Transfer-Encoding, Range-Unit
sb-gateway-version: 1
sb-project-ref: hocjpflweuppomwqkdui
x-content-type-options: nosniff
x-envoy-attempt-count: 1
x-envoy-upstream-service-time: 2
priority: u=4,i=?0
server: cloudflare
alt-svc: h3=":443"; ma=86400
server-timing: cfExtPri
```

```json
{"code":"P0001","details":null,"hint":null,"message":"Channel DMpR675dafa3X7I4 does not exist or has been deleted."}
```
